spring.application.name=streaming
# Switch the standard port to the default HTTPS port
server.port=8443
# FORCE SERVER TO LISTEN ON THE NETWORK
# 0.0.0.0 tells Spring to bind to EVERY available network interface (Wi-Fi, Ethernet, and Localhost)
server.address=0.0.0.0

# Enable SSL/TLS
server.ssl.enabled=true

# Tell Spring where to find your certificate file
server.ssl.key-store=${SSL_KEYSTORE_PATH}

# Specify the password you created during the keytool step
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}

# Specify the store type
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=keystore-it

# This will log every single incoming HTTP request
logging.level.org.springframework.web=DEBUG

# Create jpa
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url = ${DB_URL}
spring.datasource.username = ${USERNAME_DB}
spring.datasource.password = ${PASSWORD_DB}
spring.datasource.driver-class-name = org.postgresql.Driver